services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    networks:
      - backend_network

  backend:
    image: ghcr.io/${GITHUB_ACTOR}/dotnet-backend:latest
    container_name: dotnet_backend
    restart: always
    ports:
      - "5000:8080"
    depends_on:
      - db
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${MYSQL_ROOT_PASSWORD}
    networks:
      - backend_network
      - frontend_network

  frontend:
    image: ghcr.io/${GITHUB_ACTOR}/react-frontend:latest
    container_name: react_frontend
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - frontend_network

networks:
  backend_network:
  frontend_network:
