---
- name: Deploy 3-Tier Application
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - name: Verify Docker service is active
      ansible.builtin.service:
        name: docker
        state: started
        enabled: yes
      become: yes

    - name: Log in to GHCR
      community.docker.docker_login:
        registry: ghcr.io
        username: "{{ GITHUB_ACTOR }}"
        password: "{{ GITHUB_TOKEN }}"
        state: present

    - name: Deploy the application using docker-compose
      community.docker.docker_compose_v2:
        project_src: .
        state: present
        pull: always
      environment:
        MYSQL_ROOT_PASSWORD: "{{ MYSQL_ROOT_PASSWORD }}"
        DB_HOST: "{{ DB_HOST }}"
        DB_PORT: "{{ DB_PORT }}"
        DB_NAME: "{{ DB_NAME }}"
        DB_USER: "{{ DB_USER }}"
        GITHUB_ACTOR: "{{ GITHUB_ACTOR }}"
